#!/bin/bash
app="rodinia_2.0-ft" # GPU_Microbenchmark
configs=(ORIN-SASS ORIN-SASS-LINEAR-RR-32B-FRFCFS ORIN-SASS-LINEAR-RR-32B-FCFS ORIN-SASS-LINEAR-RR-256B-FRFCFS ORIN-SASS-LINEAR-RR-256B-FCFS ORIN-SASS-LINEAR-GTO-32B-FRFCFS ORIN-SASS-LINEAR-GTO-32B-FCFS ORIN-SASS-LINEAR-GTO-256B-FRFCFS ORIN-SASS-LINEAR-GTO-256B-FCFS ORIN-SASS-IPOLY-RR-32B-FRFCFS ORIN-SASS-IPOLY-RR-32B-FCFS ORIN-SASS-IPOLY-RR-256B-FRFCFS ORIN-SASS-IPOLY-RR-256B-FCFS ORIN-SASS-IPOLY-GTO-32B-FRFCFS ORIN-SASS-IPOLY-GTO-32B-FCFS ORIN-SASS-IPOLY-GTO-256B-FRFCFS ORIN-SASS-IPOLY-GTO-256B-FCFS)
mkdir -p per.kernel.stats.$app
for element in ${configs[@]}
do
    ../job_launching/get_stats.py -R -k -K -C $element -B $app | tee per.kernel.stats.$app/per.kernel.stats.rodinia_2.0-ft.$element.csv
done
