#!/bin/bash
app="rodinia_2.0-ft"
configs=(ORIN-SASS ORIN-SASS-LINEAR-RR-32B-FRFCFS ORIN-SASS-LINEAR-RR-32B-FCFS ORIN-SASS-LINEAR-RR-256B-FRFCFS ORIN-SASS-LINEAR-RR-256B-FCFS ORIN-SASS-LINEAR-GTO-32B-FRFCFS ORIN-SASS-LINEAR-GTO-32B-FCFS ORIN-SASS-LINEAR-GTO-256B-FRFCFS ORIN-SASS-LINEAR-GTO-256B-FCFS ORIN-SASS-IPOLY-RR-32B-FRFCFS ORIN-SASS-IPOLY-RR-32B-FCFS ORIN-SASS-IPOLY-RR-256B-FRFCFS ORIN-SASS-IPOLY-RR-256B-FCFS ORIN-SASS-IPOLY-GTO-32B-FRFCFS ORIN-SASS-IPOLY-GTO-32B-FCFS ORIN-SASS-IPOLY-GTO-256B-FRFCFS ORIN-SASS-IPOLY-GTO-256B-FCFS)
for element in ${configs[@]}
do
    ..plotting/plot-correlation.py -c ./per.kernel.stats.$app/per.kernel.stats.$app.$element.csv -H ./hw_run_$app/device-0/11.4/ -v -p $element
done